version: "3.5"

services:
  db:
    image: mariadb:10.11
    volumes:
      #- ./wp-data:/docker-entrypoint-initdb.d
      - "db-data:/var/lib/mysql"
    ports:
      - "3306"
    networks:
      net:
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - ./wp-app:/var/www/wp-content # wordpress content
    ports:
      - "80"
    networks:
      exposenetwork:
      net:
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: "${WEBSERVER_VIRTUAL_HOST}"
      VIRTUAL_HOST: "${WEBSERVER_VIRTUAL_HOST}"
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"

volumes:
  db-data:

networks:
  # Join proxy network for exposing http services
  exposenetwork:
    name: web_proxy
    external: true
  # Internal network for this project
  net: