version: "3.5"

services:

  wordpress:
    build: ./
    volumes:
      - ./wp-app:/var/www/wp-content # wordpress content
      - ./config/msmtprc:/etc/msmtprc:ro
    ports:
      - "80"
      - "443"
    networks:
      exposenetwork:
      net:
    depends_on:
      - mta
    environment:
      #DB_HOST: aws-rds.endpoint:3306
      #DB_PASSWORD: wordpress
      #DB_NAME: wordpress
      #DB_USER: wordpress
      WORDPRESS_SITE_URL: "${WEBSERVER_VIRTUAL_HOST}"
      VIRTUAL_HOST: "${WEBSERVER_VIRTUAL_HOST}"
      FS_METHOD: direct
      ENABLE_ACME: 'true'

  mta:
    image: namshi/smtp
    environment:
      - SMARTHOST_ADDRESS
      - MAILNAME=mta
    networks:
      net:
    restart: always

networks:
  # Join proxy network for exposing http services
  exposenetwork:
    name: web_proxy
    external: true
  # Internal network for this project
  net: